server:
  port: 8080

spring:
  application:
    name: travel-master-api
  ai:
    mcp:
      client:
        enabled: ${mcp.client.enabled}
        name: ${mcp.client.name}
        version: ${mcp.client.version}
        request-timeout: ${mcp.client.request-timeout}
        type: ${mcp.client.type}
        initialized: false
        sse:
          connections:
            tencent-cls:
              url: ${mcp.client.sse.connections.tencent-cls.url}
              sse-endpoint: ${mcp.client.sse.connections.tencent-cls.sse-endpoint}

ai:
  deepseek:
    base-url: https://api.deepseek.com
    chat-path: /chat/completions
    model: deepseek-chat
    api-key: ${DEEPSEEK_API_KEY:}

mcp:
  client:
    enabled: true
    name: tencent-mcp-server
    version: 1.0.0
    request-timeout: 60s
    type: ASYNC
    sse:
      connections:
        tencent-cls:
          url: https://mcp-api.tencent-cloud.com
          sse-endpoint: /sse/8736cac72f5dd21c
